# Standards: 0.11
---

## 5.3.3 Ensure password reuse is limited

- name: 5.3.3 - Ensure password reuse is limited (/etc/pam.d/system-auth)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    line: "{{ item }}"
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored
  with_items:
    - "password required pam_pwhistory.so remember=5"

- name: 5.3.3 - Ensure password reuse is limited (/etc/pam.d/password-auth)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    line: "{{ item }}"
  tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored
  with_items:
    - "password required pam_pwhistory.so remember=5"
